// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rentistry.domain;

import com.rentistry.domain.Account;
import com.rentistry.domain.Region;
import com.rentistry.domain.RentUser;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AccountDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AccountDataOnDemand: @Component;
    
    private Random AccountDataOnDemand.rnd = new SecureRandom();
    
    private List<Account> AccountDataOnDemand.data;
    
    public Account AccountDataOnDemand.getNewTransientAccount(int index) {
        Account obj = new Account();
        setAboutMe(obj, index);
        setAvatarFileName(obj, index);
        setAvatarKey(obj, index);
        setDefaultRegion(obj, index);
        setRentUser(obj, index);
        return obj;
    }
    
    public void AccountDataOnDemand.setAboutMe(Account obj, int index) {
        String aboutMe = "aboutMe_" + index;
        obj.setAboutMe(aboutMe);
    }
    
    public void AccountDataOnDemand.setAvatarFileName(Account obj, int index) {
        String avatarFileName = "avatarFileName_" + index;
        obj.setAvatarFileName(avatarFileName);
    }
    
    public void AccountDataOnDemand.setAvatarKey(Account obj, int index) {
        String avatarKey = "avatarKey_" + index;
        obj.setAvatarKey(avatarKey);
    }
    
    public void AccountDataOnDemand.setDefaultRegion(Account obj, int index) {
        Region defaultRegion = null;
        obj.setDefaultRegion(defaultRegion);
    }
    
    public void AccountDataOnDemand.setRentUser(Account obj, int index) {
        RentUser rentUser = null;
        obj.setRentUser(rentUser);
    }
    
    public Account AccountDataOnDemand.getSpecificAccount(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Account obj = data.get(index);
        java.lang.Long id = obj.getId();
        return Account.findAccount(id);
    }
    
    public Account AccountDataOnDemand.getRandomAccount() {
        init();
        Account obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return Account.findAccount(id);
    }
    
    public boolean AccountDataOnDemand.modifyAccount(Account obj) {
        return false;
    }
    
    public void AccountDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Account.findAccountEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Account' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.rentistry.domain.Account>();
        for (int i = 0; i < 10; i++) {
            Account obj = getNewTransientAccount(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
